##########################
# example configuration
##########################

  # API token to interact with the specified Grafana instance
  # Base URL of the Grafana instance
  grafana-url:   "http://localhost:3000"
  # SSH-URL of the Git repository to use
  private-key-file:   "<PRIVATE_KEY_FILE>"
  # Private key to use for authentication against the Git repository

  # push (export) related configurations
  push-configuration:
    # whether to export dashboards
    enable: true
    # the branch to use for exporting dashboards
    # only dashboards with match this pattern will be considered in the sync process
    filter: ""
    # the tag to determine which dashboards should be exported
    # whether the sync-tag should be kept during exporting
    push-tags: true

  # pull (import) related configurations  
  pull-configuration:
    # whether to import dashboards
    enable: true
    # the branch to use for importing dashboards
    # only dashboards with match this pattern will be considered in the sync process
    filter: ""