version: '3'
services:
  # Grafana stage one
  grafana_stage_one:
    image: grafana/grafana:8.1.2
    container_name: grafana_stage_one
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=novatec-dashboardsync-datasource
      - SSH_KNOWN_HOSTS=github.com
      - GF_ALLOWED_ORIGINS="http://localhost:3000"
    volumes:
      - ${PLUGIN_REPO}:/var/lib/grafana/plugins/
      - ${GIT_SSH_KEY}:/usr/share/grafana/.ssh
    ports:
      - 3001:3000

  # Grafana stage two
  grafana_stage_two:
    image: grafana/grafana:8.1.2
    container_name: grafana_stage_two
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
      - GF_PATHS_PROVISIONING=/usr/share/grafana/custom/
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=novatec-dashboardsync-datasource
      - SSH_KNOWN_HOSTS=github.com
      - GF_ALLOWED_ORIGINS="http://localhost:3000"
    volumes:
      - ${PLUGIN_REPO}:/var/lib/grafana/plugins/
      - ${GIT_SSH_KEY}:/usr/share/grafana/.ssh
    ports:
      - 3002:3000

