name: Build Release Version
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Install Go Dependencies
        run: |
          go mod tidy
      - name: Install Application
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
          prerelease: false
          title: "Version ${{ env.RELEASE_VERSION }}"
          files: |
            dist/*
