name: Build Data Source
on:
  push:
    branches:
      - main
jobs:
  build-plugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Install Mage
        uses: nickhstr/action-setup-mage@v1.0.0
        with:
          version: '1.11.0'
      - name: Install Go Dependencies
        run: |
          go mod tidy
          mage -v
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.2'
      - name: Install Plugin Frontend
        run: |
          yarn install --frozen-lockfile
          yarn build
      - uses: papeloto/action-zip@v1
        with:
          files: dist/
          dest: novatec-dashboardsync-datasource_${{ github.run_number }}.zip
