name: Build Prerelease Version
on:
  push:
    branches:
      - main
jobs:
  build-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.3'
      - name: Install Go Dependencies
        run: |
          go mod tidy
      - name: Install Application
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: -v
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.package-version.outputs.current-version}}-${{ github.run_number }}"
          files: |
            dist/*
